# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.setFixedSize(245, 132)  # 固定界面大小，不能拉伸,resize()可以拉伸
		Dialog.setWindowModality(QtCore.Qt.ApplicationModal)  # 阻塞父窗口
		# 窗口不显示最大化按钮、最小化按钮、关闭按钮、帮助按钮
		# Dialog.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
		Dialog.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
		Dialog.setWindowFlag(QtCore.Qt.WindowMinimizeButtonHint, False)
		Dialog.setWindowFlag(QtCore.Qt.WindowMaximizeButtonHint, False)
		Dialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
		self.pushButton = QtWidgets.QPushButton(Dialog)
		self.pushButton.setGeometry(QtCore.QRect(80, 70, 91, 31))
		font = QtGui.QFont()
		font.setFamily("Adobe Devanagari")
		font.setPointSize(12)
		self.pushButton.setFont(font)
		self.pushButton.setObjectName("pushButton")
		# 点击pushButton按钮，关闭窗口
		self.pushButton.clicked.connect(Dialog.close)
		self.label = QtWidgets.QLabel(Dialog)
		self.label.setGeometry(QtCore.QRect(40, 20, 171, 31))
		font = QtGui.QFont()
		font.setFamily("Adobe Devanagari")
		font.setPointSize(18)
		self.label.setFont(font)
		self.label.setAlignment(QtCore.Qt.AlignCenter)
		self.label.setObjectName("label")

		self.retranslateUi(Dialog)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.pushButton.setText(_translate("Dialog", "确定"))
		self.label.setText(_translate("Dialog", "任务执行完成"))
		Dialog.setWindowTitle("任务状态")
